export default {
    menus:[
        {
            key:'home',
            path:'/',
            title:'概况'
        },
        {
            key:'operate',
            path:'/operate',
            title:'运营'
        },
        {
            key:'user',
            path:'/user',
            title:'客户'
        },
        {
            key:'system',
            path:'/system',
            title:'系统'
        },
        {
            key:'sale',
            path:'/sale',
            title:'营销'
        },
        {
            key:'order',
            path:'/order',
            title:'订单'
        },
    ]
}